package com.maks.repository;

public interface IAccountServiceRepository {

    boolean checkIfUserWithSuchTokenExists(String verificationToken);

    void blockUser(Long userId);

    void unblockUser(Long userId);
}

//FIRST OF ALL CHECK IF USER WITH SUCH VERIFICATION TOKEN EXISTS
//IF THERE IS NO SUCH USER GIVE A NEGATIVE LINK TO USER
//IF EXISTS GET HIS ACCOUNT AND SET FIELD IS_ACTIVATED = TRUE

//THE SAME WITH BLOCKED ACCOUNT
//ON ADMIN PAGE ADD BUTTON WITH REFERENCE TO SERVLETE THAT
//WILL GET USER'S ACCOUNT AND SET HIS IS_BLOCK FIELD TO = TRUE

//THAN ORDINARY CHECK WILL WORK, IF THERE IS A BLOCKED USERS
//SEND HIM TO LOGIN PAGE WITH APPROPRIATE MESSAGE OF BLOCKED ACCOUNT
//SUGGEST HIM HELP AND GICE A CHANCE TO CONNECT TO ADMINISTRATOR FOR FURTHER HELP

//ALSO ADD PANEL WITH MESSAGES FROM USERS TO ADMIN PAGE AND
//MAKE SERVICE TO SEND REPLIES ON THEIR EMAILS

//ADD NEW FUNCTION BELOW LOGIN FORM - 'FORGOT MY PASSWORD'
//LET USER RESTORE HIS PASSWORD THROUGH EMAIL AS WELL
//FOR THAT HAVE TO CHANGE ADD NEW FIELD AT T_USER
//SOMETHING LIKE 'F_TEMPORARY_PASSWORD' IN ORDER NOT TO
//DELETE PREVIOUS ONE. OR NOT???

